#!/bin/bash
# 检查 SynaRoute v0.1.21 发布状态

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📦 SynaRoute v0.1.21 发布状态检查"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

REPO="EngineeMoMo/SynaRoute"
TAG="v0.1.21"

echo "🔍 检查项目："
echo "   仓库: https://github.com/$REPO"
echo "   标签: $TAG"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 快速链接"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  GitHub Actions 总览:"
echo "   https://github.com/$REPO/actions"
echo ""
echo "2️⃣  Release 工作流:"
echo "   https://github.com/$REPO/actions/workflows/release.yml"
echo ""
echo "3️⃣  发布页面 (构建完成后):"
echo "   https://github.com/$REPO/releases/tag/$TAG"
echo ""
echo "4️⃣  所有 Releases:"
echo "   https://github.com/$REPO/releases"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏗️  预期构建产物"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🍎 macOS (ARM64):"
echo "   - SynaRoute_<version>_aarch64.dmg"
echo "   - SynaRoute_<version>_aarch64.app.tar.gz"
echo ""
echo "🍎 macOS (Intel):"
echo "   - SynaRoute_<version>_x64.dmg"
echo "   - SynaRoute_<version>_x64.app.tar.gz"
echo ""
echo "🐧 Linux:"
echo "   - synaroute_<version>_amd64.AppImage"
echo "   - synaroute_<version>_amd64.deb"
echo ""
echo "🪟 Windows:"
echo "   - SynaRoute_<version>_x64-setup.exe"
echo "   - SynaRoute_<version>_x64_en-US.msi"
echo ""
echo "📄 更新器:"
echo "   - latest.json (自动更新配置)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏱️  预估时间"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   - macOS 构建: 约 15-20 分钟"
echo "   - Linux 构建: 约 10-15 分钟"
echo "   - Windows 构建: 约 10-15 分钟"
echo "   - 总耗时: 约 15-25 分钟 (并行构建)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 检查清单"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "□ 工作流已触发 (黄色圆点 🟡)"
echo "□ macOS 构建通过 (绿色勾号 ✅)"
echo "□ Linux 构建通过 (绿色勾号 ✅)"
echo "□ Windows 构建通过 (绿色勾号 ✅)"
echo "□ Release 已创建 (可在 Releases 页面看到)"
echo "□ 安装包已上传 (可下载 .dmg/.deb/.msi 等)"
echo "□ latest.json 已生成 (用于自动更新)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 提示"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "- 刷新 Actions 页面查看实时进度"
echo "- 绿色勾号 = 构建成功"
echo "- 红色叉号 = 构建失败 (查看日志)"
echo "- 黄色圆点 = 正在构建中"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
